site_name: Casey Lee
site_description: Casey Lee - Software engineer, DevOps consultant, AWS Hero
repo_url: "https://github.com/cplee/cplee.org"
theme:
  name: terminal
  custom_dir: docs/custom_theme/
  features:
    - navigation.side.hide
nav:
  - Home: 'index.md'
  - Resume: 'resume/resume.html'
markdown_extensions:
  - attr_list

extra_css:
  - style.css
