name: checks
on: [pull_request, workflow_dispatch]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Pandoc
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y pandoc
      - run: pip install -r requirements.txt
      - run: npm install -g markdownlint-cli
      - run: make